version: '3.8'
services:
  seabattle:
    build:
      context: .
    container_name: seabattle-main
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - db

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME="${MONGO_USERNAME}"
      - MONGO_INITDB_ROOT_PASSWORD=$"${MONGO_PASSWORD}"
      - MONGO_INITDB_ROOT_HOST="${MONGO_HOST}"
      - MONGO_INITDB_ROOT_PORT="${MONGO_PORT}"
      - MONGO_INITDB_ROOT_NAME="${MONGO_NAME}"

networks:
  db:
    driver: bridge
volumes:
  postgres_data:
