version: '3.8'
services:
  seabattle:
    build:
      context: api_template
    image: goseabattle
    container_name: goseabattle
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - db
  db:
    image: postgres:14.6
    restart: always
    container_name: db
    hostname: db
    environment:
      POSTGRES_DB: "seabattle"
      POSTGRES_USER: "seabattle"
      POSTGRES_PASSWORD: "seabattle"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U seabattle" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - db
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=""
      - REDIS_PORT=6379
      - REDIS_DATABASES=0
    healthcheck:
      test: [ "CMD-SHELL", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  db:
    driver: bridge
volumes:
  postgres_data:
