// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.1
// source: pb/matchmaking.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindMatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TgID int64 `protobuf:"varint,1,opt,name=tgID,proto3" json:"tgID,omitempty"`
}

func (x *FindMatchRequest) Reset() {
	*x = FindMatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_matchmaking_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMatchRequest) ProtoMessage() {}

func (x *FindMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_matchmaking_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMatchRequest.ProtoReflect.Descriptor instead.
func (*FindMatchRequest) Descriptor() ([]byte, []int) {
	return file_pb_matchmaking_proto_rawDescGZIP(), []int{0}
}

func (x *FindMatchRequest) GetTgID() int64 {
	if x != nil {
		return x.TgID
	}
	return 0
}

type FindMatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TgID int64 `protobuf:"varint,1,opt,name=tgID,proto3" json:"tgID,omitempty"`
}

func (x *FindMatchResponse) Reset() {
	*x = FindMatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_matchmaking_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMatchResponse) ProtoMessage() {}

func (x *FindMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_matchmaking_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMatchResponse.ProtoReflect.Descriptor instead.
func (*FindMatchResponse) Descriptor() ([]byte, []int) {
	return file_pb_matchmaking_proto_rawDescGZIP(), []int{1}
}

func (x *FindMatchResponse) GetTgID() int64 {
	if x != nil {
		return x.TgID
	}
	return 0
}

type MatchResultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TgIDWinner int64 `protobuf:"varint,1,opt,name=tgIDWinner,proto3" json:"tgIDWinner,omitempty"`
	TgIDLoser  int64 `protobuf:"varint,2,opt,name=tgIDLoser,proto3" json:"tgIDLoser,omitempty"`
}

func (x *MatchResultRequest) Reset() {
	*x = MatchResultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_matchmaking_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResultRequest) ProtoMessage() {}

func (x *MatchResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_matchmaking_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResultRequest.ProtoReflect.Descriptor instead.
func (*MatchResultRequest) Descriptor() ([]byte, []int) {
	return file_pb_matchmaking_proto_rawDescGZIP(), []int{2}
}

func (x *MatchResultRequest) GetTgIDWinner() int64 {
	if x != nil {
		return x.TgIDWinner
	}
	return 0
}

func (x *MatchResultRequest) GetTgIDLoser() int64 {
	if x != nil {
		return x.TgIDLoser
	}
	return 0
}

type MatchResultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *MatchResultResponse) Reset() {
	*x = MatchResultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_matchmaking_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResultResponse) ProtoMessage() {}

func (x *MatchResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_matchmaking_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResultResponse.ProtoReflect.Descriptor instead.
func (*MatchResultResponse) Descriptor() ([]byte, []int) {
	return file_pb_matchmaking_proto_rawDescGZIP(), []int{3}
}

func (x *MatchResultResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_pb_matchmaking_proto protoreflect.FileDescriptor

var file_pb_matchmaking_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x62, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x69, 0x6e, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b,
	0x69, 0x6e, 0x67, 0x22, 0x26, 0x0a, 0x10, 0x46, 0x69, 0x6e, 0x64, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x67, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x67, 0x49, 0x44, 0x22, 0x27, 0x0a, 0x11, 0x46,
	0x69, 0x6e, 0x64, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x67, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x74, 0x67, 0x49, 0x44, 0x22, 0x52, 0x0a, 0x12, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x67,
	0x49, 0x44, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x74, 0x67, 0x49, 0x44, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x67,
	0x49, 0x44, 0x4c, 0x6f, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74,
	0x67, 0x49, 0x44, 0x4c, 0x6f, 0x73, 0x65, 0x72, 0x22, 0x25, 0x0a, 0x13, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x32,
	0xaf, 0x01, 0x0a, 0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x12,
	0x4c, 0x0a, 0x09, 0x46, 0x69, 0x6e, 0x64, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1d, 0x2e, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a,
	0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1f, 0x2e, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pb_matchmaking_proto_rawDescOnce sync.Once
	file_pb_matchmaking_proto_rawDescData = file_pb_matchmaking_proto_rawDesc
)

func file_pb_matchmaking_proto_rawDescGZIP() []byte {
	file_pb_matchmaking_proto_rawDescOnce.Do(func() {
		file_pb_matchmaking_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_matchmaking_proto_rawDescData)
	})
	return file_pb_matchmaking_proto_rawDescData
}

var file_pb_matchmaking_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_matchmaking_proto_goTypes = []interface{}{
	(*FindMatchRequest)(nil),    // 0: matchmaking.FindMatchRequest
	(*FindMatchResponse)(nil),   // 1: matchmaking.FindMatchResponse
	(*MatchResultRequest)(nil),  // 2: matchmaking.MatchResultRequest
	(*MatchResultResponse)(nil), // 3: matchmaking.MatchResultResponse
}
var file_pb_matchmaking_proto_depIdxs = []int32{
	0, // 0: matchmaking.Matchmaking.FindMatch:input_type -> matchmaking.FindMatchRequest
	2, // 1: matchmaking.Matchmaking.MatchResult:input_type -> matchmaking.MatchResultRequest
	1, // 2: matchmaking.Matchmaking.FindMatch:output_type -> matchmaking.FindMatchResponse
	3, // 3: matchmaking.Matchmaking.MatchResult:output_type -> matchmaking.MatchResultResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_matchmaking_proto_init() }
func file_pb_matchmaking_proto_init() {
	if File_pb_matchmaking_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_matchmaking_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindMatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_matchmaking_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindMatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_matchmaking_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchResultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_matchmaking_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchResultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_matchmaking_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_matchmaking_proto_goTypes,
		DependencyIndexes: file_pb_matchmaking_proto_depIdxs,
		MessageInfos:      file_pb_matchmaking_proto_msgTypes,
	}.Build()
	File_pb_matchmaking_proto = out.File
	file_pb_matchmaking_proto_rawDesc = nil
	file_pb_matchmaking_proto_goTypes = nil
	file_pb_matchmaking_proto_depIdxs = nil
}
