app:
  name: 'matchmaking'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'seabattle'
tg:
  apitoken: "6466761857:AAE-D1djhHQHjD9qEVued77UJMxCQvuYm3c"
  baseURL: ""



redis:
  address: "localhost:6379"
  db: 0
  password: ""

mongo:
  address: "mongodb://localhost:27017"
  db: "sea_battle"
  collection: "fight"
postgres:
  username: "seabattle"
  password: "seabattle"
  host: "localhost"
  port: "5432"
  name: "seabattle"
  pool_max: 10

#rabbitmq:
#  rpc_server_exchange: 'rpc_server'
#  rpc_client_exchange: 'rpc_client'