seabattle:
  name: 'seabattle'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'seabattle'

postgres:
  username: "seabattle"
  password: "seabattle"
  host: "db"
  port: "5432"
  name: "seabattle"
  pool_max: 10
mongo:
  address: "mongorep://localhost:27017"
  db: "sea_battle"
  collection: "fight"
#rabbitmq:
#  rpc_server_exchange: 'rpc_server'
#  rpc_client_exchange: 'rpc_client'