seabattle:
  name: 'seabattle'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'seabattle'

postgres:
  username: "seabattle"
  password: "seabattle"
  host: "db"
  port: "5432"
  name: "seabattle"
  pool_max: 10
redis:
  address: "redis:6379"
  password: ""
  db: 0
#rabbitmq:
#  rpc_server_exchange: 'rpc_server'
#  rpc_client_exchange: 'rpc_client'