errors:
  AlreadyMarked: "already_marked"
  AlreadyDead:   "already_dead"
  AlreadySet:     "already_set"
  NotYourTurn:    "not_your_turn"
  GameEnded:     "game_ended"
  MaxShipCount:  "count_error"
  WrongLength:    "wrong_length"
  WrongPlacement:  "wrong_placement"
  AlreadyJoined:      "already_joined"
  GameOnProgress:  "game_on_progress"
picking:
  shipFirstPoint: 0
  shipSecondPoint: 1
  personReady: 2
  personsReady: 3
main:
  height: 8
  weight:

  maxShipCount: 4
  shipTypeCount: 3

shoot:
  missed: 0
  shooted: 1
  killed: 2
  lost: 3
